SELECT * FROM dataset_1;
SELECT weather,temperature from dataset_1;
SELECT DISTINCT passanger from dataset_1;
SELECT*FROM dataset_1 LIMIT 10;
SELECT * FROM dataset_1 WHERE destination = 'Home';
SELECT *FROM dataset_1 ORDER BY coupon;
select destination as Destination from dataset_1;
SELECT occupation FROM dataset_1 GROUP BY occupation;
SELECT weather ,AVG(temperature) as avg_temp FROM dataset_1 GROUP BY weather;
select weather,COUNT(temperature) as count_temp from dataset_1 group by weather;
select weather,COUNT(DISTINCT temperature) as count_dist_temp from dataset_1 group by weather;
select weather,SUM(temperature) as sum_temp from dataset_1 group by weather;
select weather,MIN(temperature) as min_temp from dataset_1 group by weather; 
select weather,MAX(temperature) as max_temp from dataset_1 group by weather;
select occupation from dataset_1 group by occupation having occupation = 'Student';
select destination,passanger from (select * from dataset_1 where passanger ='Alone');
select * from dataset_1 where weather like 'sun%';
SELECT DISTINCT temperature from dataset_1 where temperature BETWEEN 29 AND 75;
SELECT occupation from dataset_1 where occupation IN ('Sales & Related');
SELECT occupation from dataset_1 where occupation IN ('Sales & Related','Management');
